name: example
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-333.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  esp_provisioning_ble:
    path: ../
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_spinkit: ^5.2.0
  geolocator: ^9.0.2
  location: ^5.0.1
  permission_handler: ^10.4.3
  flutter_ble_lib_ios_15:
    git:
      url: https://github.com/davejlin/flutter_ble_lib_ios_15.git
      ref: master
  device_info_plus: ^9.0.2
  logger: ^2.0.1
  app_settings: ^5.0.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

