name: esp_provisioning_ble
description: A Flutter plugin that simplifies the provisioning configuration of ESP32 modules using Bluetooth Low Energy (BLE). 
version: 1.0.0
homepage: https://github.com/ogabrielinacio/esp_provisioning_ble

environment:
  sdk: '>=3.1.0-331.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^3.0.0
  cryptography: ^2.5.0
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ogabrielinacio.esp_provisioning_ble
        pluginClass: EspProvisioningBlePlugin
      ios:
        pluginClass: EspProvisioningBlePlugin
